behaviors:
  SoccerAgent:
    trainer_type: ppo
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    keep_checkpoints: 5

    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    self_play:
      save_steps: 20000        # how often to snapshot opponent
      team_change: 100000      # how often to swap opponents
      swap_steps: 2000         # how often to try opponent swap
      window: 10               # how many past opponents to keep
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200
